name: Workflow to convert Markdown files to HTML and deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install pandoc for Markdown to HTML conversion
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # Step 5: Convert all Markdown files to HTML while preserving directory structure
      - name: Convert Markdown to HTML
        run: |
          mkdir -p _site
          find . -name "*.md" -type f | while read file; do
            mkdir -p "_site/$(dirname "$file")"
            pandoc "$file" --standalone --toc -o "_site/${file%.md}.html"
          done

      # Step 6: Deploy the generated HTML files to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.head.ref }}
            git add -A
            git commit -m 'Deploy static HTML files' || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            git add -A
            git commit -m 'Deploy static HTML files' || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD:main
